import { Router } from 'express';
import { z } from 'zod';
import * as DB from '@echoid/db';
import * as Core from '@echoid/core';
import { requireAuth } from '../middleware/auth';

const { prisma, AttestationType: PrismaAttestationType } = DB;
const {
  createExpertQualificationAttestation,
  createTrustMilestoneAttestation,
  ExpertQualification,
  calculateTrustMilestone,
} = Core;

export const attestationRouter = Router();

/**
 * POST /attestations/expert
 * Create an expert qualification attestation
 */
const expertAttestationSchema = z.object({
  qualification: z.nativeEnum(ExpertQualification),
  specialization: z.array(z.string()),
});

attestationRouter.post('/expert', requireAuth, async (req, res) => {
  try {
    const { qualification, specialization } = expertAttestationSchema.parse(req.body);
    const expertAddress = req.auth!.walletAddress;

    // Create KILT attestation
    const attestation = await createExpertQualificationAttestation(
      expertAddress,
      qualification,
      specialization,
      'ECHOID_PLATFORM' // Platform issues expert credentials
    );

    // Store in database
    const dbAttestation = await prisma.attestation.create({
      data: {
        attestationId: attestation.attestationId,
        type: PrismaAttestationType.EXPERT_QUALIFICATION,
        subjectAddress: expertAddress,
        claimData: JSON.stringify(attestation.attestationData.claim),
        issuerAddress: 'ECHOID_PLATFORM',
        blockNumber: attestation.blockNumber,
        txHash: attestation.txHash,
        verified: true,
      },
    });

    res.json({
      success: true,
      attestation: {
        id: dbAttestation.id,
        attestationId: dbAttestation.attestationId,
        type: dbAttestation.type,
        claim: JSON.parse(dbAttestation.claimData),
        blockNumber: dbAttestation.blockNumber,
        txHash: dbAttestation.txHash,
      },
    });
  } catch (error) {
    console.error('Expert attestation error:', error);
    res.status(400).json({ error: 'Failed to create expert attestation' });
  }
});

/**
 * POST /attestations/milestone
 * Create a trust milestone attestation (auto-generated by platform)
 */
attestationRouter.post('/milestone', requireAuth, async (req, res) => {
  try {
    const expertAddress = req.auth!.walletAddress;

    // Calculate expert stats
    const expert = await prisma.user.findUnique({
      where: { walletAddress: expertAddress },
      include: {
        booths: true,
        reviewsReceived: true,
        sessionsAsExpert: {
          where: { status: 'COMPLETED' },
        },
      },
    });

    if (!expert) {
      return res.status(404).json({ error: 'Expert not found' });
    }

    // Calculate stats
    const totalSessions = expert.sessionsAsExpert.length;
    const ratings = expert.reviewsReceived.map((r) => r.rating);
    const averageRating = ratings.length > 0 ? ratings.reduce((a, b) => a + b, 0) / ratings.length : 0;
    const trustScore = expert.booths[0]?.trustScore || 0;

    // Determine milestone
    const milestone = calculateTrustMilestone(totalSessions, averageRating);

    // Check if this milestone already exists
    const existing = await prisma.attestation.findFirst({
      where: {
        subjectAddress: expertAddress,
        type: PrismaAttestationType.TRUST_MILESTONE,
        claimData: {
          contains: milestone,
        },
      },
    });

    if (existing) {
      return res.json({
        success: true,
        attestation: {
          id: existing.id,
          attestationId: existing.attestationId,
          type: existing.type,
          claim: JSON.parse(existing.claimData),
          existing: true,
        },
      });
    }

    // Create milestone attestation
    const attestation = await createTrustMilestoneAttestation({
      expertAddress,
      milestone,
      trustScore,
      totalSessions,
      averageRating,
    });

    // Store in database
    const dbAttestation = await prisma.attestation.create({
      data: {
        attestationId: attestation.attestationId,
        type: PrismaAttestationType.TRUST_MILESTONE,
        subjectAddress: expertAddress,
        claimData: JSON.stringify(attestation.attestationData.claim),
        issuerAddress: 'ECHOID_PLATFORM',
        blockNumber: attestation.blockNumber,
        txHash: attestation.txHash,
        verified: true,
      },
    });

    res.json({
      success: true,
      attestation: {
        id: dbAttestation.id,
        attestationId: dbAttestation.attestationId,
        type: dbAttestation.type,
        claim: JSON.parse(dbAttestation.claimData),
        blockNumber: dbAttestation.blockNumber,
        txHash: dbAttestation.txHash,
        existing: false,
      },
    });
  } catch (error) {
    console.error('Milestone attestation error:', error);
    res.status(400).json({ error: 'Failed to create milestone attestation' });
  }
});

/**
 * GET /attestations/:walletAddress
 * Get all attestations for a wallet address
 */
attestationRouter.get('/:walletAddress', async (req, res) => {
  try {
    const { walletAddress } = req.params;

    const attestations = await prisma.attestation.findMany({
      where: { subjectAddress: walletAddress },
      orderBy: { createdAt: 'desc' },
    });

    res.json({
      success: true,
      attestations: attestations.map((att) => ({
        id: att.id,
        attestationId: att.attestationId,
        type: att.type,
        claim: JSON.parse(att.claimData),
        issuer: att.issuerAddress,
        blockNumber: att.blockNumber,
        txHash: att.txHash,
        verified: att.verified,
        createdAt: att.createdAt,
      })),
    });
  } catch (error) {
    console.error('Get attestations error:', error);
    res.status(500).json({ error: 'Failed to fetch attestations' });
  }
});

/**
 * GET /attestations/verify/:attestationId
 * Verify an attestation by ID
 */
attestationRouter.get('/verify/:attestationId', async (req, res) => {
  try {
    const { attestationId } = req.params;

    const attestation = await prisma.attestation.findUnique({
      where: { attestationId },
    });

    if (!attestation) {
      return res.status(404).json({ error: 'Attestation not found' });
    }

    res.json({
      success: true,
      attestation: {
        id: attestation.id,
        attestationId: attestation.attestationId,
        type: attestation.type,
        claim: JSON.parse(attestation.claimData),
        subject: attestation.subjectAddress,
        issuer: attestation.issuerAddress,
        blockNumber: attestation.blockNumber,
        txHash: attestation.txHash,
        verified: attestation.verified,
        createdAt: attestation.createdAt,
      },
    });
  } catch (error) {
    console.error('Verify attestation error:', error);
    res.status(500).json({ error: 'Failed to verify attestation' });
  }
});
